# Generated by Django 5.2.7 on 2025-11-04 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='default_video_id',
        ),
    ]
