# Generated by Django 5.2.8 on 2025-11-17 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_country_customuser_google_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_digest',
            field=models.BooleanField(default=True, verbose_name='Resumo Semanal'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='marketing_emails',
            field=models.BooleanField(default=False, verbose_name='E-mails de Marketing'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_alerts',
            field=models.BooleanField(default=True, verbose_name='Alertas de Segurança'),
        ),
    ]
